# Makefile for the Intel Fortran compiler
# Rename this file to "Makefile" when
# installing this package on Mahuika

FC = ifort
FCFLAGS = -fPIC -Ofast
LDFLAGS = -shared

HMMextra0s.so : prsloop.o loop1.o loop2.o estep.o mstep.o
	$(FC) -o $@ $(FCFLAGS) $+ $(LDFLAGS)

%.o : %.f90
	$(FC) -c $(FCFLAGS) $<

clean :
	rm -f *.o *.so

.PHONY : clean
